### PR TITLE
removed range stuff

### LINKED ISSUE #19: Don't iterate the JP2 encoding so much
The looping of the JP2 encoder arguments was a terrible hack to try and handle a now-fixed bug in openjpeg.  Given that the bug is fixed and we haven't seen problems in a while, it would make a lot of sense to undo the rate-twiddling and `-I` flag twidding in the JP2 shell calls.  I think there's value in testing that the JP2 can be decoded, but I don't think we should loop anymore.  Either the encode operation succeeds or we fail immediately.

### PR DESCRIPTION
**Pull request by lsat12357**
fix #19

### CODE REVIEW

File: src/derivatives/jp2/make_jp2.go [hunk 1]
```diff
@@ -156,52 +155,11 @@ func (t *Transformer) makeJP2() {
...
-		if i > 50 && len(rangeQueue.queue) == 0 {
-			rangeQueue.Append(baseRate/6, baseRate/3)
-			rangeQueue.Append(baseRate*5/4, baseRate*3/2)
-		}
+	if t.testRate(baseRate) {
+		return
 	}
 
-	t.err = fmt.Errorf("no rate found for creating a valid JP2")
+	t.err = fmt.Errorf("default rate does not create a valid JP2")
```
Comment (jechols) [inline src/derivatives/jp2/make_jp2.go]: Since rates are no longer a variable factor, I'd prefer the error value not mention it at all anymore.  e.g., "couldn't create a valid JP2"

**Comment by jechols** [comment]
I wouldn't fail the review for this, but generally I'm aiming for something sort of similar to the Go commit message approach: https://golang.org/doc/contribute.html#commit_messages (note that I follow this rather inconsistently; I'm trying to start adapting to it)

In this case, something like this:

    derivatives/jp2: don't iterate over rates

    This changes our JP2 derivative code to only attempt the default rate instead of
    using that horrible RangeQueue type which was introduced to handle an openjpeg
    bug that's since been fixed.

I don't care about having "Fixes ..." in the commit message itself since we can do that in the pull request, but the majority of that Go commit guide should be something we aim to follow as we move forward.

**Comment by jechols** [comment]
Also note that in-depth description is a terrible sentence; it's just a quick example, not the perfect approach.
